<?php
$this->headTitle('Add Image');

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add Image</h1>

<p>
    Please fill out the following form and click the <i>Upload</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('category')); ?>
            <?= $this->formElement($form->get('category')); ?>
            <?= $this->formElementErrors($form->get('category')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('is_main')); ?>
            <?= $this->formElement($form->get('is_main')); ?>
            <?= $this->formElementErrors($form->get('is_main')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   



